<div style="text-align: center; color: darkblue;">

<img src="LMS Logo (1).png" alt="TIET Logo" style="width: 200px;">

### Thapar Institute of Engineering and Technology, Patiala  
### Computer Science & Engineering Department  
---
#### **UCS420: COGNITIVE COMPUTING**  
#### **LAB ASSIGNMENT- 4: NUMPY - INTRODUCTION-I**
---
    
#### <span style="color: darkred;">Student Name:</span> Smarth Kaushal   |  <span style="color: darkred;">    Roll Number: </span> 102497023   | <span style="color: darkred;">Branch:</span> BE-COPC |  <span style="color: darkred;">Sub-Section Code:</span>  2Q21  
#### <span style="color: darkred;">Submitted to:</span> Dr. Vaishali

</div>

**Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:**   
**a) Addition of 2 in all the elements**   
**b) Multiply 3 with all the elements**   
**c) Divide every element by 2**

In [1]:
import numpy as np

In [2]:
print("Enter 5 numbers to enter in the array:")
num1 = int(input("Number 1 : "))
num2 = int(input("Number 2 : "))
num3 = int(input("Number 3 : "))
num4 = int(input("Number 4 : "))
num5 = int(input("Number 5 : "))
mylist = [num1, num2, num3, num4, num5]

# Creating a 1D NumPy array with 5 elements
arr = np.array(mylist, dtype = int)
print("Original Array is   :",arr)

# (a) Adding 2 to all elements
arr_add = arr + 2

# (b) Multiplying each element by 3
arr_mul = arr * 3

# (c) Dividing each element by 2
arr_div = arr / 2

print("Original Array      :", arr)
print("After Addition      :", arr_add)
print("After Multiplication:", arr_mul)
print("After Division      :", arr_div)

Enter 5 numbers to enter in the array:


Number 1 :  12
Number 2 :  63
Number 3 :  45
Number 4 :  28
Number 5 :  79


Original Array is   : [12 63 45 28 79]
Original Array      : [12 63 45 28 79]
After Addition      : [14 65 47 30 81]
After Multiplication: [ 36 189 135  84 237]
After Division      : [ 6.  31.5 22.5 14.  39.5]


**Q.2 Questions on Basic NumPy Array:**   
**a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])**   
**b) Find the most frequent value and their indice(s) in the following arrays:**   
**i. x = np.array([1,2,3,4,5,1,2,1,1,1])**   
**ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])** 

In [3]:
# (a) Reverse the given NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])
arr_reversed = arr[::-1]
print("Reversed Array:", arr_reversed)

# (b) Find the most frequent value and its indices

# i. For x array
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_freq_x = np.bincount(x).argmax()
indices_x = np.where(x == most_freq_x)
print("Most Frequent in x:", most_freq_x, "at indices", indices_x)

# ii. For y array
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_freq_y = np.bincount(y).argmax()
indices_y = np.where(y == most_freq_y)
print("Most Frequent in y:", most_freq_y, "at indices", indices_y)


Reversed Array: [5 4 6 3 2 1]
Most Frequent in x: 1 at indices (array([0, 5, 7, 8, 9], dtype=int64),)
Most Frequent in y: 1 at indices (array([0, 1, 2], dtype=int64),)


**Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:**   
**a) Access 1st row, 2nd column**   
**b) Access 3rd row, 1st column** 


In [4]:
# Creating a 2D array
arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

# (a) Accessing 1st row, 2nd column
element_1_2 = arr[0, 1]

# (b) Accessing 3rd row, 1st column
element_3_1 = arr[2, 0]

print("Element at (1,2):", element_1_2)
print("Element at (3,1):", element_3_1)


Element at (1,2): 20
Element at (3,1): 70


**Q.4 Write program to create a 1-D NumPy array named _`<Your Name>`_ with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?** 

In [6]:
# Creating a 1D NumPy array with evenly spaced 25 numbers from 10 to 100
arr = np.linspace(10,100,25)
print("Original array      :", arr)
print("Dimensions          :", arr.ndim)
print("Shape               :", arr.shape)
print("Total Elements      :", arr.size)
print("Data Type           :", arr.dtype)
print("Total Bytes Consumed:", arr.nbytes)
print()

# Transposing using reshape
transpose_arr = arr.reshape(25, 1)
print("Transposed Array using reshape:\n", transpose_arr)

# Can we use T attribute? No, because T only works for 2D+ arrays.
print("Using .T on 1D array:", arr.T)  # No effect


Original array      : [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions          : 1
Shape               : (25,)
Total Elements      : 25
Data Type           : float64
Total Bytes Consumed: 200

Transposed Array using reshape:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using .T on 1D array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


**Q5. Create a 2-D Array of three rows and four columns, named `ucs420_<your_name>` with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as `reshaped_ ucs420_<your_name>`. Resize the array to two rows and three columns and name it as `resized_ ucs420_<your_name>`.**

In [7]:
# Creating a 2D array of 3x4 dimensions
ucs420_smarth = np.array([[10, 20, 30, 40], 
                          [50, 60, 70, 80], 
                          [90, 15, 20, 35]])

# Computing statistics
mean_val = np.mean(ucs420_smarth)
median_val = np.median(ucs420_smarth)
max_val = np.max(ucs420_smarth)
min_val = np.min(ucs420_smarth)
unique_elements = np.unique(ucs420_smarth)

print("Mean           :", mean_val)
print("Median         :", median_val)
print("Max            :", max_val)
print("Min            :", min_val)
print("Unique Elements:", unique_elements)

# Reshaping the array to 4x3
reshaped_ucs420_smarth = ucs420_smarth.reshape(4, 3)
print("Reshaped Array (4x3):\n", reshaped_ucs420_smarth)

# Resizing the array to 2x3
resized_ucs420_smarth = np.resize(ucs420_smarth, (2, 3))
print("Resized Array (2x3):\n", resized_ucs420_smarth)


Mean           : 43.333333333333336
Median         : 37.5
Max            : 90
Min            : 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
