<a href="https://colab.research.google.com/github/Smarth2005/UCS420-Cognitive-Computing-Lab-Assignments/blob/main/Python%20Basic%20Libraries%3A%20Hands-On%20Implementation/L1.%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy: A Hands-On Learning Journey
The NumPy package is the workhorse of data analysis, machine learning, and scientific computing in the python ecosystem. It vastly simplifies manipulating and crunching vectors and matrices. Some of python’s leading package rely on NumPy as a fundamental piece of their infrastructure (examples include scikit-learn, SciPy, pandas, and tensorflow). Beyond the ability to slice and dice numeric data, mastering numpy will give you an edge when dealing and debugging with advanced usecases in these libraries.

In [ ]:
import numpy as np

### **Creating Arrays**
#### What is an array?
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While Python lists contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.  
#### We can create a NumPy array (a.k.a. the mighty ndarray) by passing a python list to it and using ` np.array()`.

In [ ]:
my_list = [1,2,3,4,5,6,7,8]
arr = np.array(my_list)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
arr.shape

(8,)

#### There are often cases when we want NumPy to initialize the values of the array for us. NumPy provides methods like ones(), zeros(), and random.random() for these cases. We just pass them the number of elements we want it to generate:

In [ ]:
arr1 = np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


In [ ]:
arr1

array([1., 1., 1., 1., 1.])

#### **Note:**
##### When you use np.ones(5), it creates an array of size 5 filled with the value 1.0. NumPy defaults to `float64` for functions like np.ones() unless you specify the `dtype` parameter.

#### **Why do the Dots Appear ?**  
##### In NumPy, floating-point numbers are typically represented with a decimal point to differentiate them from integers.
##### [1. 1. 1. 1. 1.] is the same as [1.0, 1.0, 1.0, 1.0, 1.0] but uses a shorter representation.

In [ ]:
arr1 = np.ones(5, dtype = int)
print(arr1)

[1 1 1 1 1]


In [ ]:
arr2 = np.zeros(5)
print(arr2)

[0. 0. 0. 0. 0.]


In [ ]:
arr2 = np.zeros(5, dtype = int)
print(arr2)

[0 0 0 0 0]


In [ ]:
arr3 = np.random.random(3)
print(arr3)

[0.04178992 0.32554591 0.23675535]


### **Array Arithmetic**

In [ ]:
data = np.array([1,2])
ones = np.ones(2, dtype = int)
data + ones # Adding the two arrays 'data' and 'ones' position-wise(i.e. adding the values of each row)

array([2, 3])

In [ ]:
data - ones # [1-1,2-1] = [0,1]

array([0, 1])

In [ ]:
data * ones # [1*1, 2*1] = [1,2]

array([1, 2])

In [ ]:
data / ones # [1/1, 2/1]

array([1., 2.])

In [ ]:
data * data # [1*1, 2*2] = [1,4]

array([1, 4])

In [ ]:
data / data # [1/1, 2/2] = [1.0,1.0]

array([1., 1.])

In [ ]:
data * 1.6 # [1*1.6,2*1.6] = [1.6,3.2]

array([1.6, 3.2])

### **Indexing and Slicing**

In [ ]:
mylist = [1,2,3,4,5,6,7,8]
arr = np.array(mylist)
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
arr[0]

np.int64(1)

In [ ]:
arr[3]

np.int64(4)

In [ ]:
arr[0:3]

array([1, 2, 3])

In [ ]:
arr[4:7] # index 7 excluded

array([5, 6, 7])

In [ ]:
arr[3:] # array from index 3

array([4, 5, 6, 7, 8])

In [ ]:
arr[:5] # array upto index 4 (index 5 excluded)

array([1, 2, 3, 4, 5])

### **Aggregation**

In [ ]:
mylist = [23, 34, 67, 56, 98, 12, 10, 7, 79]
data = np.array(mylist)
print(data)
print("Min element =",data.min())
print("Max element =",data.max())

[23 34 67 56 98 12 10  7 79]
Min element = 7
Max element = 98


In [ ]:
newArray = np.array([1,2,3,4,5])
print("Sum of all elements of array                =", newArray.sum())
print("Average of all elements of array            =", newArray.mean())
print("Product of all elements of array            =", newArray.prod())
print("Standard deviation of all elements of array =", newArray.std())
print("Variance of array elements                  =",(newArray.std())**2)

Sum of all elements of array                = 15
Average of all elements of array            = 3.0
Product of all elements of array            = 120
Standard deviation of all elements of array = 1.4142135623730951
Variance of array elements                  = 2.0000000000000004


#### *The Beauty of NumPy is its ability  to apply everything we've looked at so far to any number of dimensions.*  
### **Creating Matrices**

In [ ]:
mat = np.array([[1,2],[3,4]])
print(mat)

[[1 2]
 [3 4]]


In [ ]:
# Multinested array
lst1 = [1,8,9,7,6]
lst2 = [4,5,6,3,2]
lst3 = [1,0,2,4,8]

matrix = np.array([lst1,lst2,lst3])

In [ ]:
type(matrix)

numpy.ndarray

In [ ]:
matrix

array([[1, 8, 9, 7, 6],
       [4, 5, 6, 3, 2],
       [1, 0, 2, 4, 8]])

In [ ]:
print(matrix)

[[1 8 9 7 6]
 [4 5 6 3 2]
 [1 0 2 4 8]]


In [ ]:
matrix.shape #gives the tuple(No. of rows, No. of cols)

(3, 5)

### **Matrix Reshaping and Transposing**

In [ ]:
matrix.reshape(5,3)

array([[1, 8, 9],
       [7, 6, 4],
       [5, 6, 3],
       [2, 1, 0],
       [2, 4, 8]])

In [ ]:
matrix.T #Transpose the matrix

array([[1, 4, 1],
       [8, 5, 0],
       [9, 6, 2],
       [7, 3, 4],
       [6, 2, 8]])

### **Matrix Indexing and Slicing**

In [ ]:
matrix

array([[1, 8, 9, 7, 6],
       [4, 5, 6, 3, 2],
       [1, 0, 2, 4, 8]])

In [ ]:
matrix.reshape(1,15)

array([[1, 8, 9, 7, 6, 4, 5, 6, 3, 2, 1, 0, 2, 4, 8]])

In [ ]:
matrix[10]

IndexError: index 10 is out of bounds for axis 0 with size 3

In [ ]:
matrix[7]

IndexError: index 7 is out of bounds for axis 0 with size 3

In [ ]:
matrix[1]

array([4, 5, 6, 3, 2])

#### **Note:**
##### Although it looks like that the matrix has been converted to 1-D Array, but it has not been. It is still a matrix with the same tuples (each row being a respective tuple) only the way of presenting the matrix or the shape of the matrix changes.

In [ ]:
matrix[:,:]

array([[1, 8, 9, 7, 6],
       [4, 5, 6, 3, 2],
       [1, 0, 2, 4, 8]])

In [ ]:
matrix[0:2,:]

array([[1, 8, 9, 7, 6],
       [4, 5, 6, 3, 2]])

In [ ]:
matrix[0:2,0:2]

array([[1, 8],
       [4, 5]])

In [ ]:
matrix[1:,3:]

array([[3, 2],
       [4, 8]])

In [ ]:
matrix[1:,2:4]

array([[6, 3],
       [2, 4]])

In [ ]:
matrix[1:,1:4]

array([[5, 6, 3],
       [0, 2, 4]])

### **Matrix Arithmetic**

In [ ]:
mylist1 = [1,2]
mylist2 = [3,4]
data = np.array([mylist1,mylist2])
ones = np.ones((2,2),dtype = int)
print("data = ")
print(data)
print("ones = ")
print(ones)

data = 
[[1 2]
 [3 4]]
ones = 
[[1 1]
 [1 1]]


In [ ]:
data + ones

array([[2, 3],
       [4, 5]])

In [ ]:
data - ones

array([[0, 1],
       [2, 3]])

In [ ]:
data * ones

array([[1, 2],
       [3, 4]])

In [ ]:
data * 4

array([[ 4,  8],
       [12, 16]])

In [ ]:
data / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [ ]:
data // 2

array([[0, 1],
       [1, 2]])

In [ ]:
data % 2

array([[1, 0],
       [1, 0]])

In [ ]:
data + data

array([[2, 4],
       [6, 8]])

In [ ]:
data * data # position-wise operation

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
data.dot(data) # How??

array([[ 7, 10],
       [15, 22]])

### **Matrix Aggregation**

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
matrix.min() # minimum element

np.int64(1)

In [ ]:
matrix.max() # maximum element

np.int64(9)

In [ ]:
matrix.sum() # sum of all elements

np.int64(45)

In [ ]:
matrix.mean() # Average of all the elements

np.float64(5.0)

In [ ]:
matrix.max(axis = 0)

array([7, 8, 9])

In [ ]:
matrix.min(axis = 1)

array([1, 4, 7])

In [ ]:
matrix.max(axis = 1)

array([3, 6, 9])

In [ ]:
matrix.prod()

np.int64(362880)

## NumPy Functions Cheat Sheet

| **Category**                | **Function**             | **Description**                                                                 |
|-----------------------------|--------------------------|---------------------------------------------------------------------------------|
| **Array Creation**          | `array()`               | Create an array.                                                               |
|                             | `zeros()`               | Create an array filled with zeros.                                             |
|                             | `ones()`                | Create an array filled with ones.                                              |
|                             | `empty()`               | Create an uninitialized array.                                                 |
|                             | `full()`                | Create an array filled with a specific value.                                   |
|                             | `arange()`              | Create an array with evenly spaced values within a given range.                 |
|                             | `linspace()`            | Create an array with evenly spaced values between two points.                   |
|                             | `logspace()`            | Create an array with logarithmically spaced values.                             |
|                             | `eye()`                 | Create a 2D identity matrix.                                                   |
|                             | `identity()`            | Create an identity matrix.                                                     |
|                             | `meshgrid()`            | Generate coordinate matrices from coordinate vectors.                           |
|                             | `empty_like()`          | Create an uninitialized array with the same shape and type as another array.    |
|                             | `zeros_like()`          | Create an array of zeros with the same shape and type as another array.         |
|                             | `ones_like()`           | Create an array of ones with the same shape and type as another array.          |
|                             | `full_like()`           | Create a filled array with the same shape and type as another array.            |
| **Array Information**       | `size`                  | Total number of elements in the array.                                         |
|                             | `shape`                 | Tuple of array dimensions.                                                     |
|                             | `ndim`                  | Number of dimensions in the array.                                             |
|                             | `dtype`                 | Data type of the array elements.                                               |
|                             | `itemsize`              | Size of each array element in bytes.                                           |
| **Array Inspection**        | `nonzero()`             | Returns indices of non-zero elements.                                          |
|                             | `where()`               | Returns elements chosen based on conditions.                                   |
|                             | `argwhere()`            | Returns indices of elements that satisfy a condition.                          |
|                             | `extract()`             | Returns elements based on a condition.                                         |
| **Array Manipulation**      | `reshape()`             | Change the shape of an array.                                                  |
|                             | `transpose()`           | Transpose the dimensions of an array.                                          |
|                             | `swapaxes()`            | Swap two axes of an array.                                                     |
|                             | `ravel()`               | Flatten an array.                                                              |
|                             | `flatten()`             | Return a flattened array copy.                                                 |
|                             | `expand_dims()`         | Expand dimensions of an array.                                                 |
|                             | `squeeze()`             | Remove single-dimensional entries from the shape.                               |
|                             | `concatenate()`         | Join arrays along an existing axis.                                            |
|                             | `hstack()`              | Stack arrays horizontally.                                                     |
|                             | `vstack()`              | Stack arrays vertically.                                                       |
|                             | `dstack()`              | Stack arrays along the third dimension.                                        |
|                             | `split()`               | Split an array into multiple sub-arrays.                                       |
|                             | `hsplit()`              | Split arrays horizontally.                                                     |
|                             | `vsplit()`              | Split arrays vertically.                                                       |
|                             | `dsplit()`              | Split arrays along the third dimension.                                        |
|                             | `tile()`                | Constructs a new array by repeating an array a specified number of times.       |
|                             | `repeat()`              | Repeats elements of an array.                                                  |
|                             | `flip()`                | Reverses the order of elements along an axis.                                   |
|                             | `roll()`                | Rolls array elements along a specified axis.                                    |
| **Mathematical Functions**  | `add()`                 | Add arrays element-wise.                                                       |
|                             | `subtract()`            | Subtract arrays element-wise.                                                  |
|                             | `multiply()`            | Multiply arrays element-wise.                                                  |
|                             | `divide()`              | Divide arrays element-wise.                                                    |
|                             | `mod()`                 | Compute the element-wise modulus.                                              |
|                             | `power()`               | Raise elements to powers element-wise.                                         |
|                             | `around()`              | Round elements to the given number of decimals.                                |
|                             | `ceil()`                | Return the ceiling of each element.                                            |
|                             | `floor()`               | Return the floor of each element.                                              |
|                             | `trunc()`               | Truncate elements to the nearest integer.                                      |
|                             | `exp()`                 | Compute the exponential of each element.                                       |
|                             | `log()`                 | Compute the natural logarithm of each element.                                  |
|                             | `log10()`               | Compute the base-10 logarithm of each element.                                  |
|                             | `log2()`                | Compute the base-2 logarithm of each element.                                   |
|                             | `sin()`                 | Compute the sine of each element.                                              |
|                             | `cos()`                 | Compute the cosine of each element.                                            |
|                             | `tan()`                 | Compute the tangent of each element.                                           |
|                             | `sqrt()`                | Compute the square root of each element.                                       |
|                             | `cbrt()`                | Compute the cube root of each element.                                         |
|                             | `square()`              | Compute the square of each element.                                            |
|                             | `clip()`                | Limits the values in an array within a specified range.                         |
|                             | `gradient()`            | Returns the gradient of an array.                                              |
|                             | `diff()`                | Calculates the n-th discrete difference along an axis.                         |
|                             | `sign()`                | Returns the sign of each element.                                              |
| **Statistical Functions**   | `sum()`                 | Compute the sum of array elements.                                             |
|                             | `prod()`                | Compute the product of array elements.                                         |
|                             | `mean()`                | Compute the mean of array elements.                                            |
|                             | `std()`                 | Compute the standard deviation of array elements.                               |
|                             | `var()`                 | Compute the variance of array elements.                                        |
|                             | `median()`              | Compute the median of array elements.                                          |
|                             | `argmin()`              | Return the indices of the minimum value.                                       |
|                             | `argmax()`              | Return the indices of the maximum value.                                       |
|                             | `cumsum()`              | Compute the cumulative sum of array elements.                                  |
|                             | `cumprod()`             | Compute the cumulative product of array elements.                               |
|                             | `corrcoef()`            | Returns the Pearson correlation coefficient matrix.                             |
|                             | `cov()`                 | Calculates the covariance matrix.                                              |
|                             | `ptp()`                 | Returns the range (max - min) of values along an axis.                          |
| **Logical Functions**       | `all()`                 | Test whether all elements evaluate to `True`.                                   |
|                             | `any()`                 | Test whether any element evaluates to `True`.                                   |
|                             | `logical_and()`         | Compute the logical AND operation element-wise.                                 |
|                             | `logical_or()`          | Compute the logical OR operation element-wise.                                  |
|                             | `logical_not()`         | Compute the logical NOT operation element-wise.                                 |
|                             | `greater()`             | Return `True` for elements greater than the second input.                       |
|                             | `less()`                | Return `True` for elements less than the second input.                          |
| **Random Functions**        | `random.rand()`         | Generate random numbers from a uniform distribution.                            |
|                             | `random.randn()`        | Generate random numbers from a normal distribution.                             |
|                             | `random.randint()`      | Generate random integers.                                                      |
|                             | `random.choice()`       | Generate a random sample from a 1D array.                                      |
|                             | `random.seed()`         | Seed the random number generator.                                              |
|                             | `random.shuffle()`      | Shuffle an array in place.                                                     |
|                             | `random.permutation()`  | Randomly permute a sequence.                                                   |
| **Linear Algebra**          | `dot()`                 | Compute the dot product of two arrays.                                         |
|                             | `matmul()`              | Perform matrix multiplication.                                                 |
|                             | `inv()`                 | Compute the inverse of a matrix.                                               |
|                             | `det()`                 | Compute the determinant of a matrix.                                           |
|                             | `eig()`                 | Compute the eigenvalues and eigenvectors of a matrix.                           |
|                             | `trace()`               | Return the sum of the diagonal elements of a matrix.                            |
|                             | `matrix_rank()`         | Calculate the rank of a matrix.                                                |
| **Fourier Transform**       | `fft.fft()`             | Compute the one-dimensional FFT.                                               |
|                             | `fft.ifft()`            | Compute the one-dimensional inverse FFT.                                        |
|                             | `fft.rfft()`            | Compute the one-dimensional FFT for real input.                                 |
|                             | `fft.irfft()`           | Compute the inverse FFT for real input.                                        |
|                             | `fft.fftshift()`        | Shift the zero-frequency component to the center of the spectrum.               |
| **I/O Functions**           | `loadtxt()`             | Load data from a text file.                                                    |
|                             | `savetxt()`             | Save data to a text file.                                                      |
|                             | `save()`                | Save arrays to a binary `.npy` file.                                           |
|                             | `load()`                | Load arrays from a binary `.npy` file.                                         |

---



In [ ]:
# Important
# copy() function and broadcasting
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr[3:] = 100

In [ ]:
print(arr)

[  1   2   3 100 100 100 100 100 100]


In [ ]:
arr1 = arr
print(arr)
print(arr1)

[  1   2   3 100 100 100 100 100 100]
[  1   2   3 100 100 100 100 100 100]


In [ ]:
arr1[3:] = 500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [ ]:
print(arr)
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[  1   2   3 500 500 500 500 500 500]


#### **Why Use copy()?**
Without explicitly copying an array, assigning one array to another (e.g., arr2 = arr1) creates a reference. Any changes made to the new array (arr2) will also affect the original (arr1), as they both point to the same memory location. Using copy() avoids this issue

In [ ]:
arr1= arr.copy()

In [ ]:
arr1[3:]=1000
print(arr)
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [ ]:
# Some conditions very useful in Exploratory Data Analysis
arr < 2

array([ True, False, False, False, False, False, False, False, False])

In [ ]:
arr > 450

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [ ]:
arr*8

array([   8,   16,   24, 4000, 4000, 4000, 4000, 4000, 4000])

In [ ]:
arr%2

array([1, 0, 1, 0, 0, 0, 0, 0, 0])

In [ ]:
arr/2

array([  0.5,   1. ,   1.5, 250. , 250. , 250. , 250. , 250. , 250. ])

In [ ]:
arr[arr<600]

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [ ]:
arr[arr<100]

array([1, 2, 3])

In [ ]:
arr = np.arange(1,10)

In [ ]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(1,10,2)

In [ ]:
print(arr)

[1 3 5 7 9]


In [ ]:
np.linspace(1,10,50) # equally spaced points between 1 and 10

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

These 50 points are including 1 and 10.